name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      # Commented to disable CI before tomorrow
      # - name: Run tests
      #   run: yarn test:ci
      #   env:
      #     NODE_ENV: test
